### ISSUE TITLE
BD osc tuning

### ISSUE THREAD

**Issue by Juzokas** [Normalised/ProkDrumsEditor#10]
Hello,
it seems to be a problem to tune oscillators for BD on OSX. The slider is jumping between ±20, ±60, ±115 Hz, thus making impossible to tune in specific frequency. Some keyboard input for the values would be really wonderful, as well as correct slider scaling.

**Comment by Thonk-Steve** [comment]
Try this:

Use Ctrl + click for fine control
Then Ctrl + shift for extra fine control

you have to click mouse *after* you hold the keyboard shortcut.

**Comment by Juzokas** [comment]
Thanks! These are wonderful modules. Love them :))
