### ISSUE TITLE
Prok BD module only boots alternately on power on

### ISSUE THREAD

**Issue by fuzzySi** [Normalised/ProkDrumsEditor#14]
Hi Steve
Sorry, not an editor issue but can't find any contact details for developer. 
My Prok BD module only boots on alternate times - ie when I turn power on to modular, if it starts, it won't next time & vice versa. I can cycle the power but would rather not need to. Not sure if this is a firmware issue or hardware, but can you pass this on to the module developer? 
Cheers, Simon

**Comment by Thonk-Steve** [comment]
Hi Simon,

The module can be sensitive like this when the power supply in the case is
being pushed close to its limit. Have you tried unplugging a few power
hungry modules in your case first to see if it changes how the Prok boots?

Steve

**Comment by fuzzySi** [comment]
Cheers Steve. It's connected to a small splitter box for the power, maybe this isn't adequate. I'll try connecting it in a different way.
Thanks for your help, Simon
