### ISSUE TITLE
"launch the editor application"... ok but what do i launch ?

### ISSUE THREAD

**Issue by ggodzillai** [Normalised/ProkDrumsEditor#15]
i don't understand what app to launch once the prok is connected.

**Comment by Normalised** [comment]
What operating system are you using?

**Comment by ggodzillai** [comment]
Windows 10.

**Comment by Normalised** [comment]
Did you download the windows application from here :
https://normalised.github.io/ProkDrumsEditor/

You should download and unzip this:

https://github.com/Normalised/ProkDrumsEditor/releases/download/v0.1-beta.2/ProkModularEditor_Win_Beta2.zip

**Comment by ggodzillai** [comment]
Hi,
yes i downloaded and unzip this... but what do i have to look for next ? .exe ? what is .jar .json ? never saw that

**Comment by Normalised** [comment]
the app is launched by ProkModularEditor.exe

.exe is a typical windows extensions for applications.

**Comment by ggodzillai** [comment]
hoooo... i get it. Now that you said there's a .exe i tried to remove my antivirus (basic windows defender) and it worked. My antivirus was deleting the .exe when unziping.
thx
