### ISSUE TITLE
Problems loading SD card banks

### ISSUE THREAD

**Issue by rithma** [Normalised/ProkDrumsEditor#21]
so...
I save a set of 16 custon Bassdrum patches onto a FAT32 SD card, 
I power cycle the module with the trigger pressed,  the module takes a few extra moments to boot, but when it boots, its just the stock sounds in there.   What am I doing wrong?

cheers

**Comment by Thonk-Steve** [comment]
Hey,

Could you email your patches to support@thonk.co.uk please? Unless you
don't mind uploading them here.

Regards

Steve
Thonk

**Comment by rithma** [comment]
I'll leave them here...
[BD_RITHMA.zip](https://github.com/Normalised/ProkDrumsEditor/files/3911564/BD_RITHMA.zip)

**Comment by Normalised** [comment]
You'll need to name them specifically for them to load.

KICK_0.PRK
KICK_1.PRK
KICK_2.PRK
etc..
then for 11 to 16 its :
KICK_A.PRK
KICK_B.PRK
KICK_C.PRK
KICK_D.PRK
KICK_E.PRK
KICK_F.PRK

**Comment by rithma** [comment]
renamed **KICK_0.prk** thru **KICK_9.prk**  and **KICK_A.prk** thru **KICK_F.prk**

same problem,   no SD card load.      Does the SD card need to be named anything in particular?

**Comment by rithma** [comment]
... just tried changing all suffix to caps   **.PRK**

still no luck

**Comment by rithma** [comment]
is there somebody on here who could try loading my BD patches?   Maybe this way I can narrow down the issue. 
[prokBD.zip](https://github.com/Normalised/ProkDrumsEditor/files/3924446/prokBD.zip)

**Comment by Normalised** [comment]
I tried with 2 different SD cards and the patches loaded fine onto my BD module. 

The modules are much more sensitive than computers with different SD card formatting settings.

If you are on windows, check the formatting settings for the SD card. I always make sure to choose the default in the 'Allocation Unit Size' setting.

**Comment by rithma** [comment]
ALLRIGHT!!!   I reflowed the SD card pins and all is working well now.   Thanks so much for your help!
