### ISSUE TITLE
Editor not seeing the module, oversized PROK Logo and thats it. Noise on CP module

### ISSUE THREAD

**Issue by liomus** [Normalised/ProkDrumsEditor#24]
It wouldnt recognize either of both modules I build, SN and CP. Weither it's plugged to the system or not, with or without sd etc etc, The editor just shows an oversized logo and thats it. I'm on mac 10.14 and my usb cable works. Both modules work as it should on the system except the CP that has this very unpleasant constant noise. By experience I can guaranty its very well build and still can't figure where that come from.

**Comment by Thonk-Steve** [comment]
Hi Liomus,

You have it powered by Eurorack power still when you're plugging the USB
cable into the computer?

Also they are definitely data USB cables, not just charging USB cables?

Thanks

Steve

**Comment by liomus** [comment]
The fourth cable test was the right one, can't believe the issue was that simple.. and Thank you

**Comment by Thonk-Steve** [comment]
You're welcome, enjoy!
