### ISSUE TITLE
DrumCentral hangs on spinner when updating firmware to v5

### ISSUE THREAD

**Issue by sawtoothwave** [Normalised/ProkDrumsEditor#30]
Bug report

It appears my firmware has loaded properly but the spinner never stops spinning. I took a chance and closed DrumCentral after 15 minutes of no obvious activity and then disconnected my module and it worked fine. Same thing happened with the other 3 modules as I upgraded them from v3 to v5.

I’m using a MacBook Pro from 2013 running High Sierra.

**Comment by Normalised** [comment]
Thanks, this seems fairly common on OSX. Glad the modules are working fine though.
If you do face any firmware issues let us know, even if they do look unresponsive we haven't encountered an actual bricked module for firmware upgrades yet.

**Comment by sawtoothwave** [comment]
Glad to know it’s a known issue and hasn’t bricked anything!
