### ISSUE TITLE
[feature request] coarse & fine controls for sine frequency (Snare)

### ISSUE THREAD

**Issue by stutzjr** [Normalised/ProkDrumsEditor#8]
I've only tried the editor on my Snare module so far.  I've been thinking about how to add a bit more precision to the sine frequency controls **without having to change the existing data structures** - here's an idea...
Would it be possible to implement the following?:
For sine A & B frequency, a course control that has a range 0 to 5kHz with 0.5 kHz increments,
and a fine control that has a range like -500Hz to +1kHz.
When the user edits these controls, the frequency value rendered and saved is the sum of the fine and coarse control, limited to values above the minimum possible frequency.
When a preset is loaded or the frequency is changed by an external event, the controls are reset as follows: the coarse control is assigned the value of the "thousands" digit, and the fine control is assigned the value of the "remainder".  This way the user still has a range of fine control either side of the current value, and the existing data structures would not need to be changed.

example: User wants to set Sine A frequency to 1250 Hz:
coarse = 1kHz, fine = 250 Hz, sum = 1250, OR
coarse = 500 Hz, fine = 750 Hz, sum = 1250, OR
coarse = 1.5kHz, fine = -250Hz, sum = 1250
example: preset or external event sets Sine B frequency to 1234 Hz:
coarse control is set to 1 thousand Hz,
fine control is set to the remainder 234 Hz.

**Comment by Normalised** [comment]
Thanks for the idea.
I think I'd rather implement a way of being able to enter the values directly.

You can hold shift when you drag the sliders to get finer control of the values, although its still not accurate enough for really specific tunings.
