### ISSUE TITLE
Trouble shooting the device not showing up in Win7

### ISSUE THREAD

**Issue by bovaflux** [Normalised/ProkDrumsEditor#9]
I was having a problem getting the module to connect via USB. I tried a couple of cables and different USB ports but the device would just show up in device manager as a not correctly installed USB serial device. Using the steps on this page (https://www.pjrc.com/teensy/troubleshoot.html) I figured out that on Win7 I would need to download and install a driver. Once I did this all worked fine, but it would be good to add some help to the editor docs to save people time. :)

**Comment by Normalised** [comment]
Yes, good point.
